'use strict';
let content=null;let dirty=false;
const $=selector=>document.querySelector(selector);const getPath=(object,path)=>path.split('.').reduce((value,key)=>value?.[Number.isInteger(Number(key))?Number(key):key],object);const setPath=(object,path,value)=>{const parts=path.split('.');let cursor=object;for(let i=0;i<parts.length-1;i++)cursor=cursor[Number.isInteger(Number(parts[i]))?Number(parts[i]):parts[i]];cursor[parts.at(-1)]=value};
async function request(url,options={}){const response=await fetch(url,{headers:{Accept:'application/json',...(options.body&&typeof options.body==='string'?{'Content-Type':'application/json'}:{})},...options});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed');return payload}
function showToast(message,error=false){const toast=$('#toast');toast.textContent=message;toast.classList.toggle('error',error);toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,3500)}
function updateSaveState(){const state=$('#saveState');state.textContent=dirty?'Unsaved changes':'All changes saved';state.classList.toggle('dirty',dirty)}
function markDirty(){dirty=true;updateSaveState()}
function imageEditor(slot,image){return `<div class="image-editor stacked" data-slot="${slot}"><img src="${escapeAttr(image)}" alt="Destination image preview"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif"><button class="btn small upload" type="button">Replace image</button><button class="link-danger remove" type="button">Remove upload</button><small>JPG, PNG, WebP or GIF · max 5 MB</small></div>`}
function escapeAttr(value){return String(value||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function renderDynamicEditors(){
  $('#stepsEditor').innerHTML=content.how.steps.map((step,i)=>`<article class="mini-card">${imageEditor(`how.steps.${i}.iconImage`,step.iconImage)}<b>Step ${i+1}</b><label>Number<input data-field="how.steps.${i}.number" value="${escapeAttr(step.number)}" maxlength="4"></label><label>Title<input data-field="how.steps.${i}.title" value="${escapeAttr(step.title)}"></label><label>Description<textarea data-field="how.steps.${i}.description" rows="4">${escapeAttr(step.description)}</textarea></label></article>`).join('');
  $('#destinationsEditor').innerHTML=content.destinations.items.map((item,i)=>`<article class="mini-card destination-edit">${imageEditor(`destinations.items.${i}.image`,item.image)}<label>Category<input data-field="destinations.items.${i}.tag" value="${escapeAttr(item.tag)}"></label><label>Name<input data-field="destinations.items.${i}.title" value="${escapeAttr(item.title)}"></label><label>Location<input data-field="destinations.items.${i}.location" value="${escapeAttr(item.location)}"></label><label>Description<textarea data-field="destinations.items.${i}.description" rows="3">${escapeAttr(item.description)}</textarea></label></article>`).join('');
  $('#impactStatsEditor').innerHTML=content.impact.stats.map((stat,i)=>`<article class="mini-card"><b>Impact statistic ${i+1}</b><label>Value<input data-field="impact.stats.${i}.value" value="${escapeAttr(stat.value)}"></label><label>Label<input data-field="impact.stats.${i}.label" value="${escapeAttr(stat.label)}"></label><label>Description<textarea data-field="impact.stats.${i}.description" rows="3">${escapeAttr(stat.description)}</textarea></label></article>`).join('');
  $('#journeyFeaturesEditor').innerHTML=content.journey.features.map((feature,i)=>`<article class="mini-card"><b>Journey feature ${i+1}</b><label>Title<input data-field="journey.features.${i}.title" value="${escapeAttr(feature.title)}"></label><label>Description<textarea data-field="journey.features.${i}.description" rows="3">${escapeAttr(feature.description)}</textarea></label></article>`).join('');
  const storiesEditor=$('#storiesEditor');if(storiesEditor)storiesEditor.innerHTML=content.stories.items.map((story,i)=>`<article class="mini-card">${imageEditor(`stories.items.${i}.avatarImage`,story.avatarImage)}<b>Story ${i+1}</b><label>Rating symbols<input data-field="stories.items.${i}.rating" value="${escapeAttr(story.rating)}"></label><label>Quote<textarea data-field="stories.items.${i}.quote" rows="4">${escapeAttr(story.quote)}</textarea></label><div class="fields two"><label>Initials<input data-field="stories.items.${i}.initials" value="${escapeAttr(story.initials)}"></label><label>Name<input data-field="stories.items.${i}.name" value="${escapeAttr(story.name)}"></label></div><label>Location<input data-field="stories.items.${i}.location" value="${escapeAttr(story.location)}"></label></article>`).join('')
}
function bindForm(){document.querySelectorAll('[data-field]').forEach(field=>{const value=getPath(content,field.dataset.field);if(field.value!==value)field.value=value||'';field.addEventListener('input',()=>{setPath(content,field.dataset.field,field.value);markDirty()})});document.querySelectorAll('.image-editor').forEach(editor=>{const input=editor.querySelector('input[type=file]'),upload=editor.querySelector('.upload'),remove=editor.querySelector('.remove'),preview=editor.querySelector('img');const image=getPath(content,editor.dataset.slot);if(image)preview.src=image;upload.dataset.label=upload.textContent;upload.addEventListener('click',()=>input.click());input.addEventListener('change',()=>input.files[0]&&uploadImage(editor,input.files[0]));remove.addEventListener('click',()=>removeImage(editor))})}
async function uploadImage(editor,file){if(file.size>5*1024*1024)return showToast('Image must be 5 MB or smaller.',true);const button=editor.querySelector('.upload');button.disabled=true;button.textContent='Uploading…';try{const result=await request(`/api/admin/upload?slot=${encodeURIComponent(editor.dataset.slot)}`,{method:'POST',headers:{'Content-Type':file.type},body:file});setPath(content,editor.dataset.slot,result.url);editor.querySelector('img').src=`${result.url}?v=${Date.now()}`;showToast('Image published successfully.')}catch(error){showToast(error.message,true)}finally{button.disabled=false;button.textContent=button.dataset.label||'Replace image';editor.querySelector('input').value=''}}
async function removeImage(editor){if(!confirm('Remove this upload and restore the default image?'))return;try{const result=await request(`/api/admin/image?slot=${encodeURIComponent(editor.dataset.slot)}`,{method:'DELETE'});setPath(content,editor.dataset.slot,result.url);editor.querySelector('img').src=result.url;showToast('Upload removed and default image restored.')}catch(error){showToast(error.message,true)}}
async function save(){const button=$('#saveButton');button.disabled=true;button.textContent='Saving…';try{content=await request('/api/admin/content',{method:'PUT',body:JSON.stringify(content)});dirty=false;updateSaveState();showToast('Landing page changes published.')}catch(error){showToast(error.message,true)}finally{button.disabled=false;button.textContent='Save changes'}}
async function loadRegistrations(){const list=$('#registrationsList');try{const records=await request('/api/admin/registrations');if(!records.length){list.innerHTML='<p class="empty-list">No registrations have been submitted yet.</p>';return}list.innerHTML=`<table><thead><tr><th>Pass ID</th><th>Visitor</th><th>Visit</th><th>Group</th><th>Amount</th><th>Payment</th><th>Submitted</th></tr></thead><tbody>${records.slice().reverse().map(record=>{const guests=Object.values(record.groups||{}).reduce((sum,value)=>sum+Number(value||0),0);const payment=record.paymentStatus==='PAID'?'PAID':record.paymentStatus==='PENDING'?'PENDING':record.paymentStatus==='PAY_AT_OFFICE'?'AT OFFICE':'DEMO';return `<tr><td><strong>${escapeAttr(record.id)}</strong></td><td>${escapeAttr(record.fullName)}</td><td>${escapeAttr(record.visitDate)}</td><td>${guests}</td><td>₱${Number(record.amount||0).toFixed(2)}</td><td>${escapeAttr(record.paymentMethod)} <span class="status-demo">${payment}</span></td><td>${escapeAttr(new Date(record.createdAt).toLocaleString())}</td></tr>`}).join('')}</tbody></table>`}catch(error){list.innerHTML=`<p class="empty-list">${escapeAttr(error.message)}</p>`}}
async function openDashboard(){content=await request('/api/content');$('#loginView').hidden=true;$('#dashboardView').hidden=false;renderDynamicEditors();bindForm();updateSaveState();loadRegistrations()}
$('#loginForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter,error=$('#loginError');button.disabled=true;error.textContent='';try{await request('/api/admin/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});await openDashboard()}catch(problem){error.textContent=problem.message}finally{button.disabled=false}});
$('#saveButton').addEventListener('click',save);$('#previewButton').addEventListener('click',()=>window.open('/','ecopass-preview'));$('#logoutButton').addEventListener('click',async()=>{await request('/api/admin/logout',{method:'POST'});location.reload()});window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
$('#refreshRegistrations').addEventListener('click',loadRegistrations);
(async()=>{try{const session=await request('/api/admin/session');if(session.authenticated)await openDashboard();else $('#loginView').hidden=false}catch{$('#loginView').hidden=false;$('#loginError').textContent='The server is unavailable.'}})();
