'use strict';

process.env.ADMIN_PASSWORD = 'test-only-admin-password';
process.env.SESSION_SECRET = 'test-only-session-secret-with-sufficient-length';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { start, sanitizeContent } = require('./server');

test('public landing page has no inline editing controls and only the required visitor ID upload', async () => {
  const html = await fs.readFile(path.join(__dirname, 'ecopass.html'), 'utf8');
  const adminHtml = await fs.readFile(path.join(__dirname, 'admin.html'), 'utf8');
  const adminJs = await fs.readFile(path.join(__dirname, 'admin.js'), 'utf8');
  const adminCss = await fs.readFile(path.join(__dirname, 'admin.css'), 'utf8');
  const landingCss = await fs.readFile(path.join(__dirname, 'landing.css'), 'utf8');
  const landingJs = await fs.readFile(path.join(__dirname, 'landing.js'), 'utf8');
  assert.equal((html.match(/type=["']file["']/gi) || []).length, 1);
  assert.match(html, /name="discountId"[^>]+type="file"/);
  assert.doesNotMatch(html, /contenteditable/i);
  assert.doesNotMatch(html, /indexedDB/i);
  assert.match(html, /data-content="hero\.titleLine1"/);
  assert.match(html, /data-favicon/);
  assert.doesNotMatch(html, /data-image="hero\.phoneImage"/);
  assert.match(html, /data-image="hero\.backgroundImage"/);
  assert.match(html, /data-image="how\.backgroundImage"/);
  assert.match(html, /data-image="how\.phoneImage"/);
  assert.doesNotMatch(html, /data-image="how\.leavesImage"/);
  assert.match(html, /<dialog class="how-modal" id="how-modal"/);
  assert.match(html, /<dialog class="pass-modal" id="pass-modal"/);
  assert.match(html, /data-pass-modal-open/);
  assert.match(html, /data-content="registration\.fullNameLabel"/);
  assert.match(html, /data-content="registration\.visitDateLabel"/);
  assert.match(html, /data-content="registration\.groupTitle"/);
  assert.match(html, /data-content="registration\.paymentMethods\.4"/);
  assert.match(html, /Special:FilePath\/GCash_logo\.svg/);
  assert.match(html, /Special:FilePath\/Maya_logo\.svg/);
  assert.match(html, /Special:FilePath\/Mastercard_2019_logo\.svg/);
  assert.match(html, /Special:FilePath\/Visa_2021\.svg/);
  assert.doesNotMatch(html, /www\.paymongo\.com\/favicon\.ico|payment-logo-credit/);
  assert.match(html, /data-reopen-checkout/);
  assert.match(landingJs, /window\.open\(url\|\|'about:blank'/);
  assert.match(landingJs, /ecopass-checkout-return/);
  assert.match(landingJs, /window\.matchMedia\('\(max-width: 700px\)'\)/);
  assert.doesNotMatch(html, /iframe[^>]+checkout\.paymongo\.com/i);
  assert.match(html, /data-download-pass/);
  assert.match(html, /property="og:image" content="https:\/\/ecopass-production\.up\.railway\.app\/ecopass-social-card\.png"/);
  assert.match(html, /name="twitter:card" content="summary_large_image"/);
  assert.match(landingJs, /link\.download=`EcoPass-\$\{currentPass\.id\}\.png`/);
  assert.match(landingJs, /toBlob\(resolve,'image\/png'/);
  assert.doesNotMatch(landingJs, /EcoPass-\$\{currentPass\.id\}\.html|text\/html/);
  assert.doesNotMatch(html, /Hotel Accommodation|Booked Rooms|Mode of Travel|Round Trip/);
  assert.doesNotMatch(html, /<section[^>]+id="how"/);
  assert.match(html, /data-image="impact\.backgroundImage"/);
  assert.match(html, /data-image="impact\.emblemImage"/);
  assert.match(html, /data-image="impact\.leavesImage"/);
  assert.match(adminHtml, /data-slot="hero\.backgroundImage"/);
  assert.match(adminHtml, /data-slot="hero\.benefits\.0\.iconImage"/);
  assert.match(adminHtml, /data-slot="hero\.benefits\.1\.iconImage"/);
  assert.match(adminHtml, /data-slot="hero\.benefits\.2\.iconImage"/);
  assert.match(adminHtml, /data-slot="brand\.faviconImage"/);
  assert.doesNotMatch(adminHtml, /data-slot="hero\.phoneImage"/);
  assert.match(adminHtml, /data-slot="how\.backgroundImage"/);
  assert.match(adminHtml, /data-slot="how\.phoneImage"/);
  assert.match(adminJs, /how\.steps\.\$\{i\}\.iconImage/);
  assert.doesNotMatch(adminHtml, /data-slot="how\.leavesImage"/);
  assert.match(adminHtml, /data-slot="impact\.backgroundImage"/);
  assert.match(adminHtml, /data-slot="impact\.emblemImage"/);
  assert.match(adminHtml, /data-slot="impact\.leavesImage"/);
  assert.match(html, /data-content="hero\.benefits\.0\.label"/);
  assert.match(html, /data-image="hero\.benefits\.0\.iconImage"/);
  assert.match(html, /data-image="how\.steps\.0\.iconImage"/);
  assert.match(html, /data-content="impact\.stats\.0\.description"/);
  assert.match(html, /data-content="journey\.features\.0\.title"/);
  assert.doesNotMatch(html, /data-content="stories\.items\.0\.quote"/);
  assert.match(html, /data-content="support\.title"/);
  assert.match(html, /data-link="support\.mapEmbedUrl"/);
  assert.match(html, /data-content="cta\.secondaryButton"/);
  assert.match(html, /data-content="footer\.copyright"/);
  assert.match(html, /data-content="footer\.contactLink"/);
  assert.match(html, /data-content="footer\.helpLink"/);
  assert.doesNotMatch(html, /data-image="stories\.items\.0\.avatarImage"/);
  assert.match(html, /data-image="cta\.leavesImage"/);
  assert.match(adminHtml, /data-field="hero\.benefits\.0\.label"/);
  assert.match(adminHtml, /id="impactStatsEditor"/);
  assert.match(adminHtml, /id="journeyFeaturesEditor"/);
  assert.doesNotMatch(adminHtml, /id="storiesEditor"/);
  assert.match(adminHtml, /data-field="support\.address"/);
  assert.match(adminHtml, /data-field="support\.mapEmbedUrl"/);
  assert.match(adminHtml, /data-field="registration\.title"/);
  assert.match(adminHtml, /data-field="registration\.paymentMethods\.4"/);
  assert.match(adminHtml, /id="registrationsList"/);
  assert.match(adminHtml, /data-slot="cta\.leavesImage"/);
  assert.match(adminHtml, /data-field="footer\.contactLink"/);
  assert.match(adminHtml, /data-field="footer\.helpLink"/);
  assert.match(html, /data-image="brand\.logoImage"/);
  assert.match(html, /data-image="cta\.backgroundImage"/);
  assert.match(html, /data-image="cta\.phoneImage"/);
  assert.doesNotMatch(html, /class="site-header/);
  assert.match(html, /class="hero-logo/);
  assert.doesNotMatch(html, /class="promise-strip/);
  assert.doesNotMatch(html, /class="sun"/);
  assert.doesNotMatch(landingCss, /\.hero-visual:(?:before|after)/);
  assert.doesNotMatch(landingCss, /\.sun\{/);
  assert.match(landingCss, /\.hero-frame\{[^}]*border:0/);
  assert.match(landingCss, /\.hero-background\{[^}]*object-fit:contain/);
  assert.match(landingCss, /\.cta-sun\{/);
  assert.match(landingCss, /\.cta-leaves\{/);
  assert.match(adminCss, /\[hidden\]\{display:none!important\}/);
});

test('content sanitizer keeps the schema and strips control characters', () => {
  assert.equal(sanitizeContent({ registration: { paymentMethods: ['GCash', 'Maya', 'Bank Transfer'] } }).registration.paymentMethods[2], 'Credit/Debit Card');
  const content = sanitizeContent({ hero: { title: 'Hello\u0000 world', steps: 'ignored' }, unknown: 'discarded' });
  assert.equal(content.hero.title, 'Hello world');
  assert.equal(content.hero.phoneImage, undefined);
  assert.equal(content.hero.image, '/ecopass-hero-upload-transparent.png');
  assert.equal(content.unknown, undefined);
  assert.equal(content.brand.name, 'EcoPass');
});

test('server protects writes and persists authenticated content updates', async t => {
  const contentFile = path.join(__dirname, 'data', 'site-content.json');
  const registrationFile = path.join(__dirname, 'data', 'registrations.json');
  let original = null;
  let originalRegistrations = null;
  try { original = await fs.readFile(contentFile); } catch {}
  try { originalRegistrations = await fs.readFile(registrationFile); } catch {}
  const server = await start(0);
  t.after(async () => {
    await new Promise(resolve => server.close(resolve));
    if (original) await fs.writeFile(contentFile, original); else await fs.rm(contentFile, { force: true });
    if (originalRegistrations) await fs.writeFile(registrationFile, originalRegistrations); else await fs.rm(registrationFile, { force: true });
  });
  const base = `http://127.0.0.1:${server.address().port}`;
  const publicResponse = await fetch(`${base}/api/content`);
  assert.equal(publicResponse.status, 200);
  const current = await publicResponse.json();
  const health = await (await fetch(`${base}/health`)).json();
  assert.equal(health.status, 'ok');
  assert.equal(health.adminConfigured, true);
  const onlineNotReady = await fetch(`${base}/api/registrations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName: 'Test Tourist', address: 'Sipalay City, Philippines', contact: '0917 000 0000', visitDate: '2099-10-10', stay: '3D / 2N', groups: { adult: 2, foreign: 0, senior: 0, child: 1 }, paymentMethod: 'GCash' }) });
  assert.equal(onlineNotReady.status, 503);
  const unsignedWebhook = await fetch(`${base}/api/paymongo/webhook`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ data: { type: 'checkout_session.payment.paid', livemode: false } }) });
  assert.equal(unsignedWebhook.status, 401);
  const registration = await fetch(`${base}/api/registrations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fullName: 'Test Tourist', address: 'Sipalay City, Philippines', contact: '0917 000 0000', visitDate: '2099-10-10', stay: '3D / 2N', groups: { adult: 2, foreign: 0, senior: 0, child: 1 }, paymentMethod: 'Pay at Tourism Office (Cash)' }) });
  assert.equal(registration.status, 201);
  const registrationResult = await registration.json();
  assert.match(registrationResult.pass.id, /^ECP-20991010-[A-F0-9]{8}$/);
  assert.equal(registrationResult.pass.amount, 100);
  assert.equal(registrationResult.pass.paymentStatus, 'PAY_AT_OFFICE');
  assert.match(registrationResult.qrDataUrl, /^data:image\/png;base64,/);
  const verifiedPass = await (await fetch(`${base}/api/passes/${registrationResult.pass.id}`)).json();
  assert.equal(verifiedPass.fullName, 'Test Tourist');
  const verificationPage = await fetch(`${base}/verify/${registrationResult.pass.id}`);
  assert.equal(verificationPage.status, 200);
  assert.match(await verificationPage.text(), /Payment due at tourism office/);

  const denied = await fetch(`${base}/api/admin/content`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(current) });
  assert.equal(denied.status, 401);

  const login = await fetch(`${base}/api/admin/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password: 'test-only-admin-password' }) });
  assert.equal(login.status, 200);
  const cookie = login.headers.get('set-cookie').split(';')[0];
  const adminRegistrations = await fetch(`${base}/api/admin/registrations`, { headers: { Cookie: cookie } });
  assert.equal(adminRegistrations.status, 200);
  assert.equal((await adminRegistrations.json())[0].id, registrationResult.pass.id);
  const tinyPng = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64');
  const backgroundUpload = await fetch(`${base}/api/admin/upload?slot=how.backgroundImage`, { method: 'POST', headers: { 'Content-Type': 'image/png', Cookie: cookie }, body: tinyPng });
  assert.equal(backgroundUpload.status, 201);
  const uploadedBackground = await backgroundUpload.json();
  assert.match(uploadedBackground.url, /^\/uploads\/how-backgroundImage-/);
  const afterBackgroundUpload = await (await fetch(`${base}/api/content`)).json();
  assert.equal(afterBackgroundUpload.how.backgroundImage, uploadedBackground.url);
  assert.equal(afterBackgroundUpload.hero.backgroundImage, '/ecopass-cream-texture.png');
  const backgroundRemoval = await fetch(`${base}/api/admin/image?slot=how.backgroundImage`, { method: 'DELETE', headers: { Cookie: cookie } });
  assert.equal(backgroundRemoval.status, 200);
  assert.equal((await backgroundRemoval.json()).url, '/ecopass-cream-texture.png');
  const benefitIconUpload = await fetch(`${base}/api/admin/upload?slot=hero.benefits.0.iconImage`, { method: 'POST', headers: { 'Content-Type': 'image/png', Cookie: cookie }, body: tinyPng });
  assert.equal(benefitIconUpload.status, 201);
  const uploadedBenefitIcon = await benefitIconUpload.json();
  assert.match(uploadedBenefitIcon.url, /^\/uploads\/hero-benefits-0-iconImage-/);
  assert.equal((await (await fetch(`${base}/api/content`)).json()).hero.benefits[0].iconImage, uploadedBenefitIcon.url);
  const benefitIconRemoval = await fetch(`${base}/api/admin/image?slot=hero.benefits.0.iconImage`, { method: 'DELETE', headers: { Cookie: cookie } });
  assert.equal(benefitIconRemoval.status, 200);
  assert.equal((await benefitIconRemoval.json()).url, '/ecopass-benefit-qr.svg');
  const modalIconUpload = await fetch(`${base}/api/admin/upload?slot=how.steps.0.iconImage`, { method: 'POST', headers: { 'Content-Type': 'image/png', Cookie: cookie }, body: tinyPng });
  assert.equal(modalIconUpload.status, 201);
  const uploadedModalIcon = await modalIconUpload.json();
  assert.match(uploadedModalIcon.url, /^\/uploads\/how-steps-0-iconImage-/);
  assert.equal((await (await fetch(`${base}/api/content`)).json()).how.steps[0].iconImage, uploadedModalIcon.url);
  const modalIconRemoval = await fetch(`${base}/api/admin/image?slot=how.steps.0.iconImage`, { method: 'DELETE', headers: { Cookie: cookie } });
  assert.equal(modalIconRemoval.status, 200);
  assert.equal((await modalIconRemoval.json()).url, '/ecopass-step-destination.svg');
  const faviconUpload = await fetch(`${base}/api/admin/upload?slot=brand.faviconImage`, { method: 'POST', headers: { 'Content-Type': 'image/png', Cookie: cookie }, body: tinyPng });
  assert.equal(faviconUpload.status, 201);
  const uploadedFavicon = await faviconUpload.json();
  assert.match(uploadedFavicon.url, /^\/uploads\/brand-faviconImage-/);
  assert.equal((await (await fetch(`${base}/api/content`)).json()).brand.faviconImage, uploadedFavicon.url);
  const faviconRemoval = await fetch(`${base}/api/admin/image?slot=brand.faviconImage`, { method: 'DELETE', headers: { Cookie: cookie } });
  assert.equal(faviconRemoval.status, 200);
  assert.equal((await faviconRemoval.json()).url, '/ecopass-logo-v2.png');
  const emblemUpload = await fetch(`${base}/api/admin/upload?slot=impact.emblemImage`, { method: 'POST', headers: { 'Content-Type': 'image/png', Cookie: cookie }, body: tinyPng });
  assert.equal(emblemUpload.status, 201);
  const uploadedEmblem = await emblemUpload.json();
  assert.match(uploadedEmblem.url, /^\/uploads\/impact-emblemImage-/);
  assert.equal((await (await fetch(`${base}/api/content`)).json()).impact.emblemImage, uploadedEmblem.url);
  const emblemRemoval = await fetch(`${base}/api/admin/image?slot=impact.emblemImage`, { method: 'DELETE', headers: { Cookie: cookie } });
  assert.equal(emblemRemoval.status, 200);
  assert.equal((await emblemRemoval.json()).url, '/ecopass-impact-emblem.png');
  const avatarUpload = await fetch(`${base}/api/admin/upload?slot=stories.items.0.avatarImage`, { method: 'POST', headers: { 'Content-Type': 'image/png', Cookie: cookie }, body: tinyPng });
  assert.equal(avatarUpload.status, 201);
  const uploadedAvatar = await avatarUpload.json();
  assert.match(uploadedAvatar.url, /^\/uploads\/stories-items-0-avatarImage-/);
  assert.equal((await (await fetch(`${base}/api/content`)).json()).stories.items[0].avatarImage, uploadedAvatar.url);
  const avatarRemoval = await fetch(`${base}/api/admin/image?slot=stories.items.0.avatarImage`, { method: 'DELETE', headers: { Cookie: cookie } });
  assert.equal(avatarRemoval.status, 200);
  assert.match((await avatarRemoval.json()).url, /^https:\/\/images\.unsplash\.com\//);
  current.hero.title = 'Persisted integration test title';
  current.stories.items[0].quote = 'Persisted integration test story';
  const saved = await fetch(`${base}/api/admin/content`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Cookie: cookie }, body: JSON.stringify(current) });
  assert.equal(saved.status, 200);
  assert.equal((await saved.json()).hero.title, 'Persisted integration test title');
  const reread = await (await fetch(`${base}/api/content`)).json();
  assert.equal(reread.hero.title, 'Persisted integration test title');
  assert.equal(reread.stories.items[0].quote, 'Persisted integration test story');
});
